Create scaffold and logic controller movements
Nany-fork/ledger_account pull request #10
Opened 2022-02-03 20:34 UTC by Nany-fork

For not authorized merged [PR](https://github.com/Nany-fork/ledger_account/pull/7).

2022-02-03 22:10 UTC, luisAzcuaga requested changes
Nice work, just take a look at my suggestions! ✨

2022-02-03 22:10 UTC, luisAzcuaga commented on app/models/movement.rb
> +  belongs_to :account
Thanks to this relation, you could easily do what I told in the previous comment. If you don't want to reach me, then look for the `before_create` hook. :)

2022-02-03 22:10 UTC, luisAzcuaga commented on app/views/movement_types/_form.html.erb
> +    <%= form.label :name, style: "display: block" %>
Avoid using inline styles, always prefer using class! ✨  (code looks cleaner this way)

2022-02-03 22:10 UTC, luisAzcuaga commented on app/views/movements/_movement.html.erb
> +      <td><%= movement.name %></td>
I always love to recommend using tags, helper. (Is up to you changing it)
This line would change to:
```erb
<%= tag.td movement.name %>
```
That doesn't save up too much space, huh?
But take a look at this scenario
```erb
<% if @something.present? %>
  <td><%= @something.name %></td>
<% end %>
```
Could be changed to:
```erb
<%= tag.td @something.name if @something.present? %>
```

2022-02-04 19:18 UTC, itsmeurbi requested changes
Didn't you see my comments [here](https://github.com/Nany-fork/ledger_account/pull/7/files)?
There still a couple of things pending, like all model validations

We had a conversation yesterday about how to create your initial categories and movement types. You need to populate that values through the seeds file. There's no need for controllers if nobody will manage those resources 🤔

2022-02-04 19:18 UTC, itsmeurbi commented on app/controllers/movements_controller.rb
> +    # if params[:movement][:movement_type_id] == '1'
?

2022-02-04 19:18 UTC, itsmeurbi commented on app/views/movement_types/_form.html.erb
> +    <%= form.label :name, style: "display: block" %>
@Nany-fork

2022-02-07 23:48 UTC, itsmeurbi approved these changes
I'd say looks good to go 👍

2022-02-08 00:01 UTC, Nany-fork commented
## Creation of movements and categories 

# validations movement 
- minumum of the name and descripcion
- you can not register a date later than the current one
- you can register a new category_movement
-update the balance with (incomes, egress, payment)

2022-02-08 00:01 UTC, merged