Config to heroku
Nany-fork/ledger_account pull request #11
Opened 2022-02-08 01:02 UTC by Nany-fork

## Basic heroku config

- with out AWS SES for now
- config the .env file 
- database.yml

2022-02-08 14:44 UTC, 3zcurdia commented on Gemfile
> +  gem "pg", "~> 1.1"
la idea es que utilices el ambiente de producción mas cercano a tu ambiente local

2022-02-08 14:44 UTC, 3zcurdia commented on app/views/layouts/application.html.erb
> +    <% if notice %>
este cambio podría ir en otro PR ya que Heroku no depende de ello

2022-02-08 15:25 UTC, itsmeurbi requested changes
Same comments as Ezcurdia

2022-02-09 01:10 UTC, Nany-fork commented on Gemfile
> +  gem "pg", "~> 1.1"
![image](https://user-images.githubusercontent.com/95006480/153102606-406608ce-b81b-4913-896a-a226cf83f3aa.png)

Si no pongo la misma version con la que se instalo el proyecto me da ese error, o no importa si no pongo el group :production ?

2022-02-09 17:10 UTC, itsmeurbi commented on Gemfile
> +  gem "pg"
It's already defined [here](https://github.com/Nany-fork/ledger_account/pull/11/files#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR13)
We don't need this

2022-02-09 17:45 UTC, 3zcurdia commented on Gemfile
> +  gem "pg", "~> 1.1"
el error dice:
```
You cannot specify the same gem twice with different version requirements
```

2022-02-09 19:00 UTC, merged