Asyn form movements
Nany-fork/ledger_account pull request #12
Opened 2022-02-08 15:32 UTC by Nany-fork

This PR will have
- Add modal to make a new category in the form of movement
- Select box using Ajax Jquery (I still don't get this one)

2022-02-08 15:59 UTC, Nany-fork commented
![image](https://user-images.githubusercontent.com/95006480/153025465-e67fb0f6-5dcf-4bc3-b253-7180d74e87ef.png)
![image](https://user-images.githubusercontent.com/95006480/153025558-c2bb100c-777a-4cbe-a1e8-bcb568e8358e.png)

Se me paso boton mi boton, lo corrijo

2022-02-08 17:08 UTC, Nany-fork commented
![image](https://user-images.githubusercontent.com/95006480/153038287-a92bebfa-dc8c-43b6-aaa2-7e07613ba30a.png)
![image](https://user-images.githubusercontent.com/95006480/153038672-42ae1ec7-5324-4bcb-ad5f-009468e1be6c.png)

2022-02-08 21:58 UTC, itsmeurbi approved these changes
Seems to be legit!
Well done 👍

2022-02-08 23:02 UTC, 3zcurdia requested changes
Antes de usar el stack de hotwired déjalo con un stack de rails básico

2022-02-08 23:02 UTC, 3zcurdia commented on app/views/movement_categories/new.html.erb
> +<%= turbo_frame_tag "modal" do %>
Creo que el turbo frame no es necesario

2022-02-09 00:54 UTC, Nany-fork commented
https://user-images.githubusercontent.com/95006480/153100775-9e8900ff-efd2-465a-b6be-328003c9f19c.mp4

2022-02-09 00:55 UTC, Nany-fork commented on app/views/movement_categories/new.html.erb
> +<%= turbo_frame_tag "modal" do %>
Ya lo borre :3

2022-02-09 01:12 UTC, itsmeurbi approved these changes
Seems to be legit! 😃

2022-02-09 01:21 UTC, merged