Creating account model and creation account after register
Nany-fork/ledger_account pull request #4
Opened 2022-01-29 20:11 UTC by Nany-fork

## I have created account model wich attributes:

- balance:integer by default 0
- status:sttring by default health
- user:references 

## custom registration
 I have read the custom registration with devise and i tried to create a user controller and inherit from devise but it never worked so i read that you can **Association Reference** a model with the relation ORM has_onewith account and this works for me , everty time that every time i sign up i create an account only once

2022-01-30 01:51 UTC, itsmeurbi requested changes

2022-01-30 01:51 UTC, itsmeurbi commented on app/models/user.rb
> +    @user = User.last
:alert:
What If a new user it's created just after the current one? Instead you should use `self` to reference user being created.
This could be done in a single line

2022-01-30 03:46 UTC, Nany-fork commented on app/models/user.rb
> +    @user = User.last
so can be 
`  def self.create_account
   @user = :user  ... `

2022-01-30 03:47 UTC, itsmeurbi commented on app/models/user.rb
> +  def self.create_account
No idea what you tried to do making this a class method :mequedeasíira:
I meant using `self` as the record itself, not in the method

2022-01-30 03:48 UTC, itsmeurbi commented on app/models/user.rb
> +  def self.create_account
Tho, is this actually working?
I'd rely on tests, but they doesn't exists. Test this behavior manually and come back here with your findings

2022-01-30 04:17 UTC, Nany-fork commented on app/models/user.rb
> +  def self.create_account
:aceckto:

2022-01-30 04:23 UTC, Nany-fork commented on app/models/user.rb
> +  def self.create_account
well in this point works , but  I think I misunderstood what you were trying to tell me about the self

2022-01-30 04:37 UTC, itsmeurbi commented on app/models/user.rb
> +    @user = User.find(self.id)
I need you to debug the code and see what `self` is
You're overworking here. Again all this can be done in a single line hehe

2022-01-30 14:23 UTC, itsmeurbi commented on app/models/user.rb
> +    Account.create(user: self)
What if for some reason record is invalid? What will happen?

2022-01-30 18:19 UTC, Nany-fork commented on app/models/user.rb
> +    Account.create(user: self)
well a test manually , I made a mistake on purpose in the password, email, leaving things blank and if there is no registration there is no account.

I don't understand how to validate everything in a line

2022-01-30 18:21 UTC, Nany-fork commented on app/models/user.rb
> +    Account.create(user: self)
it gives me errors if i do
`@user = user: self ` or 
`@user = (user: self)` or 
`@user = current_user`

2022-01-30 21:15 UTC, itsmeurbi commented on app/models/user.rb
> +    Account.create(user: self)
I meant account record being invalid, not user 
In any case I wanted you to discover that if `account` records is invalid having only a user(suppose it requires a minimum initial value) this will not raise an exception and user will end up without any account assigned
This can easily be done adding a bang to the create method. That way if record is invalid, it raise an exception and user is not created

```
Account.create!(user: self)
```

2022-01-30 21:45 UTC, Nany-fork commented on app/models/user.rb
> +    Account.create(user: self)
I didn't know I could do that, thank you

2022-01-31 14:11 UTC, itsmeurbi approved these changes

2022-01-31 16:27 UTC, merged